name: hello_world
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15    
  table_calendar: ^3.0.9
  local_auth: ^2.2.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  uuid: ^4.0.0
  image_picker: ^1.0.4
  flutter_emoji: ">= 2.5.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
